TARGET_SIM   ?= 
TARGET_FLAGS ?= $(RISCV_TARGET_FLAGS)


RISCV_PREFIX   ?= riscv64-unknown-elf-
RISCV_GCC      ?= $(RISCV_PREFIX)gcc
RISCV_OBJCOPY  ?= $(RISCV_PREFIX)objcopy
RISCV_GCC_OPTS ?= -nostdlib
LDSCRIPT       ?= $(ROOTDIR)/../../linkers/riscv32.ld

COMPILE_TARGET=\
	$$(RISCV_GCC) $(1) $$(RISCV_GCC_OPTS) \
		-I$(ROOTDIR)/riscv-test-env/ \
		-I$(ROOTDIR)/riscv-test-env/p/ \
		-I$(TARGETDIR)/$(RISCV_TARGET)/ \
		-T$(LDSCRIPT) $$< \
		-o $$(@);
  
  
  
